version: '3.9'
services:
  db:
    image: postgres
    container_name: postgresSB
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bdusuarios
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data